// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VKITActivityManager.Models;

#nullable disable

namespace VKITActivityManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608082425_HoatDongNoiBat")]
    partial class HoatDongNoiBat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VKITActivityManager.Models.AnhUuDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("UuDiemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UuDiemId");

                    b.ToTable("AnhUuDiems");
                });

            modelBuilder.Entity("VKITActivityManager.Models.CauHoiThuongGap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauHoi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int");

                    b.Property<string>("TraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CauHoiThuongGaps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CauHoi = "Học phí của Viện Công nghệ Việt - Hàn như thế nào?",
                            NgayTao = new DateTime(2026, 6, 8, 15, 24, 20, 297, DateTimeKind.Local).AddTicks(3125),
                            PhanLoai = 0,
                            TraLoi = "<p>Học phí tại VKIT được tính theo tín chỉ, dao động khoảng <strong style='color: #c62828;'>15.000.000đ - 18.000.000đ/học kỳ</strong> tùy thuộc vào hệ đào tạo Kỹ sư hay Cử nhân.</p><p>Đặc biệt, sinh viên có cơ hội nhận các gói học bổng doanh nghiệp giảm từ 25% đến 50% học phí nếu đạt thành tích tốt.</p>"
                        },
                        new
                        {
                            Id = 2,
                            CauHoi = "Các phương thức xét tuyển năm 2026 là gì?",
                            NgayTao = new DateTime(2026, 6, 8, 15, 24, 20, 297, DateTimeKind.Local).AddTicks(3129),
                            PhanLoai = 0,
                            TraLoi = "<p>Năm 2026, Viện áp dụng <strong>04 phương thức xét tuyển chính</strong> công bằng:</p><ol><li>Xét tuyển kết quả thi tốt nghiệp THPT 2026.</li><li>Xét tuyển học bạ THPT theo tổ hợp 3 môn (Điểm TB lớp 12 hoặc 3 học kỳ).</li><li>Xét điểm thi Đánh giá năng lực của ĐHQG TP.HCM 2026.</li><li>Xét điểm thi Đánh giá đầu vào đại học V-SAT 2026.</li></ol>"
                        },
                        new
                        {
                            Id = 3,
                            CauHoi = "Giới thiệu ngành Công nghệ thông tin",
                            NgayTao = new DateTime(2026, 6, 8, 15, 24, 20, 297, DateTimeKind.Local).AddTicks(3132),
                            PhanLoai = 1,
                            TraLoi = "<h5 style='color: #0d47a1; font-weight: bold;'>NGÀNH CÔNG NGHỆ THÔNG TIN (Chuẩn Hàn Quốc)</h5><p>Đào tạo chuyên sâu về <strong>Kỹ nghệ phần mềm, Trí tuệ nhân tạo (AI) và An toàn thông tin</strong>.</p><ul><li>Thực hành 100% tại phòng Lab hiện đại.</li><li>Thực tập thực tế tại doanh nghiệp công nghệ lớn từ năm thứ 3.</li><li>Cơ hội chuyển tiếp du học 2+2 nhận song bằng đại học quốc tế.</li></ul>"
                        },
                        new
                        {
                            Id = 4,
                            CauHoi = "Giới thiệu ngành Công nghệ kỹ thuật ô tô",
                            NgayTao = new DateTime(2026, 6, 8, 15, 24, 20, 297, DateTimeKind.Local).AddTicks(3135),
                            PhanLoai = 2,
                            TraLoi = "<h5 style='color: #0d47a1; font-weight: bold;'>NGÀNH CÔNG NGHỆ KỸ THUẬT Ô TÔ</h5><p>Trang bị kiến thức về thiết kế hệ thống, chế tạo, kiểm định và bảo dưỡng ô tô thông minh, xe điện.</p><p>Sinh viên được thực hành trực tiếp tại các xưởng cơ khí động lực liên kết doanh nghiệp quy mô lớn.</p>"
                        },
                        new
                        {
                            Id = 5,
                            CauHoi = "Giới thiệu ngành Quản trị kinh doanh",
                            NgayTao = new DateTime(2026, 6, 8, 15, 24, 20, 297, DateTimeKind.Local).AddTicks(3137),
                            PhanLoai = 3,
                            TraLoi = "<h5 style='color: #0d47a1; font-weight: bold;'>NGÀNH QUẢN TRỊ KINH DOANH</h5><p>Đào tạo kiến thức khởi nghiệp, quản trị chiến lược, marketing số toàn cầu. Chương trình học tích hợp phương pháp làm việc chuẩn tư duy doanh nghiệp đa quốc gia.</p>"
                        });
                });

            modelBuilder.Entity("VKITActivityManager.Models.ChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanAnh");

                    b.Property<string>("DuongDanVideo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuongDanVideo");

                    b.Property<string>("MoTaNgan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTaNgan");

                    b.Property<int?>("NganhId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("PhanLoai")
                        .HasColumnType("int")
                        .HasColumnName("PhanLoai");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe");

                    b.Property<string>("TieuDe2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TieuDe2");

                    b.HasKey("Id");

                    b.ToTable("HoatDong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDongChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenNganhId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDePhu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenNganhId");

                    b.ToTable("HoatDongChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDongNoiBat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HoatDongNoiBats");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HocPhi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViApDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocPhiGiam50")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LaDongPhu")
                        .HasColumnType("bit");

                    b.Property<string>("MucHocPhi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NganhDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhSachHocPhi");
                });

            modelBuilder.Entity("VKITActivityManager.Models.LoaiHocBong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauNen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSuat")
                        .HasColumnType("int");

                    b.Property<string>("TenHocBong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.PhanLoaiVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenPhanLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhanLoaiVideos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenPhanLoai = "Video Giới thiệu (Toàn màn hình)"
                        },
                        new
                        {
                            Id = 2,
                            TenPhanLoai = "Video Danh sách (Ngang ở dưới)"
                        });
                });

            modelBuilder.Entity("VKITActivityManager.Models.SinhVienHocBong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiHocBongId")
                        .HasColumnType("int");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiHocBongId");

                    b.ToTable("SinhVienHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.UuDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauNen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenUuDiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UuDiems");
                });

            modelBuilder.Entity("VKITActivityManager.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTaNgan")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanLoaiVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhanLoaiVideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("VKITActivityManager.Models.AnhUuDiem", b =>
                {
                    b.HasOne("VKITActivityManager.Models.UuDiem", "UuDiem")
                        .WithMany("DanhSachHinhAnh")
                        .HasForeignKey("UuDiemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UuDiem");
                });

            modelBuilder.Entity("VKITActivityManager.Models.HoatDongChuyenNganh", b =>
                {
                    b.HasOne("VKITActivityManager.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany("HoatDongChuyenNganhs")
                        .HasForeignKey("ChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenNganh");
                });

            modelBuilder.Entity("VKITActivityManager.Models.SinhVienHocBong", b =>
                {
                    b.HasOne("VKITActivityManager.Models.LoaiHocBong", "LoaiHocBong")
                        .WithMany("SinhVienHocBongs")
                        .HasForeignKey("LoaiHocBongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHocBong");
                });

            modelBuilder.Entity("VKITActivityManager.Models.Video", b =>
                {
                    b.HasOne("VKITActivityManager.Models.PhanLoaiVideo", "PhanLoaiVideo")
                        .WithMany("Videos")
                        .HasForeignKey("PhanLoaiVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhanLoaiVideo");
                });

            modelBuilder.Entity("VKITActivityManager.Models.ChuyenNganh", b =>
                {
                    b.Navigation("HoatDongChuyenNganhs");
                });

            modelBuilder.Entity("VKITActivityManager.Models.LoaiHocBong", b =>
                {
                    b.Navigation("SinhVienHocBongs");
                });

            modelBuilder.Entity("VKITActivityManager.Models.PhanLoaiVideo", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("VKITActivityManager.Models.UuDiem", b =>
                {
                    b.Navigation("DanhSachHinhAnh");
                });
#pragma warning restore 612, 618
        }
    }
}
